var HexFieldErrorType = {
  // Primitive
  NOT_STRING_ERROR: 'NOT_STRING_ERROR',
  NOT_INT_ERROR: 'NOT_INT_ERROR',
  NOT_FLOAT_ERROR: 'NOT_FLOAT_ERROR',
  NOT_BOOL_ERROR: 'NOT_BOOL_ERROR',
  NOT_POSITIVE_INT_ERROR: 'NOT_POSITIVE_INT_ERROR',
  NOT_POSITIVE_FLOAT_ERROR: 'NOT_POSITIVE_FLOAT_ERROR',
  NOT_ARRAY_ERROR: 'NOT_ARRAY_ERROR',
  NOT_OBJECT_ERROR: 'NOT_OBJECT_ERROR',

  EMPTY_ERROR: 'EMPTY_ERROR',
  LENGTH_OVERFLOW_ERROR: 'LENGTH_OVERFLOW_ERROR',
  INVALID_EMAIL_ERROR: 'INVALID_EMAIL_ERROR',
  INVALID_ENG_NUM_ERROR: 'INVALID_ENG_NUM_ERROR',
  FILE_NOT_EXIST_ERROR: 'FILE_NOT_EXIST_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  PARAM_MISSING: 'PARAM_MISSING',
  ITEM_DUPLICATED_ERROR: 'ITEM_DUPLICATED_ERROR',
  ITEM_NOT_FOUND_ERROR: 'ITEM_NOT_FOUND_ERROR',
  UNSUPPORTED_METHOD: 'UNSUPPORTED_METHOD',
  INVALID_REF_TYPE_ERROR: 'INVALID_REF_TYPE_ERROR',
};

module.exports = HexFieldErrorType;
